### ISSUE TITLE
Matcher does not work with behave 1.2.6

### ISSUE THREAD

**Issue by fhanspach** [cuescience/goat#7]
Using goat with the current dev version of behave (1.2.6) raises the following exception:
```Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/behave_runner.py", line 294, in <module>
    _BehaveRunner(my_config, base_dir).run()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_bdd_utils.py", line 91, in run
    number_of_tests = self._get_number_of_tests()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_bdd_utils.py", line 211, in _get_number_of_tests
    for feature in self._get_features_to_run():
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/behave_runner.py", line 231, in _get_features_to_run
    self.__real_runner.run()
  File "/venv/lib/python3.6/site-packages/behave/runner.py", line 733, in run
    return self.run_with_paths()
  File "/venv/lib/python3.6/site-packages/behave/runner.py", line 738, in run_with_paths
    self.load_step_definitions()
  File "/venv/lib/python3.6/site-packages/behave/runner.py", line 719, in load_step_definitions
    exec_file(os.path.join(path, name), step_module_globals)
  File "/venv/lib/python3.6/site-packages/behave/runner.py", line 364, in exec_file
    exec(code, globals_, locals_)
  File "experience/tests/steps/steps.py", line 3, in <module>
    from goat.matcher import GoatMatcher
  File "/venv/lib/python3.6/site-packages/goat/matcher.py", line 8, in <module>
    from goat import model
  File "/venv/lib/python3.6/site-packages/goat/model.py", line 9, in <module>
    class Argument(model.Argument):
AttributeError: module 'behave.model' has no attribute 'Argument'
```

It seems some models of behave have moved to another file (`models_core.py`).

Fixing this is urgent because the older behave versions do not work with python 3.6 anymore.
